import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { QueryClientCustomProvider } from "@/modules/core/providers/QueryClientCustomProvider";
import { DiProvider } from "@/modules/core/contexts/DiContext";
import { ErrorBoundaryProvider } from "@/modules/core/providers/ErrorBoundaryProvider";
import { composeProviders } from "@/modules/core/utils/compose-providers";
import { Navbar } from "@/modules/core/components/navbar";
import { getService } from "@/modules/core/utils/di-utils";
import { PortfolioService } from "@/modules/portfolio/services/portfolio-service";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.svg",
  },
};

const Provider = composeProviders([
  ErrorBoundaryProvider,
  DiProvider,
  QueryClientCustomProvider,
]);

const portfolioService = getService(PortfolioService);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          <Toaster position="top-right" />
          <Navbar
            items={portfolioService.getItemMenus()}
            icon={{
              src: "/favicon.svg",
              title: "Portfolio",
            }}
          />
          {children}
        </Provider>
      </body>
    </html>
  );
}
